-- Warehouse configuration reference

SHOW WAREHOUSES;

-- Verify auto-suspend
SHOW PARAMETERS LIKE 'AUTO_SUSPEND'
IN WAREHOUSE INGEST_WH;

SHOW PARAMETERS LIKE 'AUTO_SUSPEND'
IN WAREHOUSE TRANSFORM_WH;

SHOW PARAMETERS LIKE 'AUTO_SUSPEND'
IN WAREHOUSE BI_WH;
