-- ============================================
-- RAW Layer: S3 JSON Ingestion
-- ============================================

USE DATABASE PROJECT_DB;
USE SCHEMA RAW;
USE WAREHOUSE INGEST_WH;

-- File format
CREATE OR REPLACE FILE FORMAT JSON_FF
TYPE = 'JSON'
STRIP_OUTER_ARRAY = FALSE;

-- External stage
CREATE OR REPLACE STAGE RAW_CUSTOMER_STAGE
URL = 's3://snowflake-end-to-end-scd2/raw/customer/'
STORAGE_INTEGRATION = s3_snowflake_int
FILE_FORMAT = JSON_FF;

-- RAW table
CREATE OR REPLACE TABLE RAW_CUSTOMER (
    RAW_PAYLOAD VARIANT,
    METADATA_FILENAME STRING,
    METADATA_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stream (append-only)
CREATE OR REPLACE STREAM RAW_CUSTOMER_STREAM
ON TABLE RAW_CUSTOMER
APPEND_ONLY = TRUE;

-- Initial load (full backfill)
COPY INTO RAW_CUSTOMER (RAW_PAYLOAD, METADATA_FILENAME, METADATA_ROW_NUMBER)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @RAW_CUSTOMER_STAGE/full/
)
FILE_FORMAT = JSON_FF;
