CREATE OR REPLACE VIEW ANALYTICS.DIM_CUSTOMER AS
SELECT
    CUSTOMER_SK,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    EMAIL_ID,
    PHONE_NUMBER,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_SEGMENT,
    CREDIT_RATING,
    CUSTOMER_STATUS,
    SOURCE_SYSTEM,
    EFFECTIVE_START_DT,
    LOAD_TIMESTAMP
FROM SILVER.SILVER_CUSTOMER
WHERE IS_CURRENT = TRUE;
