-- ============================================
-- BRONZE Layer: RAW to Structured Table
-- ============================================

USE DATABASE PROJECT_DB;
USE SCHEMA BRONZE;
USE WAREHOUSE TRANSFORM_WH;

-- Target table
CREATE OR REPLACE TABLE BRONZE_CUSTOMER (
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    EMAIL_ID STRING,
    PHONE_NUMBER STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    CUSTOMER_SEGMENT STRING,
    CREDIT_RATING STRING,
    CUSTOMER_STATUS STRING,
    SOURCE_SYSTEM STRING,
    RECORD_HASH STRING,
    LOAD_DATE DATE,
    LOAD_TIMESTAMP TIMESTAMP
);

-- Task: RAW → BRONZE
CREATE OR REPLACE TASK RAW_TO_BRONZE_CUSTOMER_TASK
WAREHOUSE = TRANSFORM_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.RAW_CUSTOMER_STREAM')
AS
INSERT INTO BRONZE_CUSTOMER
SELECT
    RAW_PAYLOAD:CUSTOMER_ID::STRING,
    RAW_PAYLOAD:CUSTOMER_NAME::STRING,
    RAW_PAYLOAD:EMAIL_ID::STRING,
    RAW_PAYLOAD:PHONE_NUMBER::STRING,
    RAW_PAYLOAD:CITY::STRING,
    RAW_PAYLOAD:STATE::STRING,
    RAW_PAYLOAD:COUNTRY::STRING,
    RAW_PAYLOAD:CUSTOMER_SEGMENT::STRING,
    RAW_PAYLOAD:CREDIT_RATING::STRING,
    RAW_PAYLOAD:CUSTOMER_STATUS::STRING,
    RAW_PAYLOAD:SOURCE_SYSTEM::STRING,
    RAW_PAYLOAD:RECORD_HASH::STRING,
    CURRENT_DATE,
    CURRENT_TIMESTAMP
FROM RAW.RAW_CUSTOMER_STREAM;

-- Activate task
ALTER TASK RAW_TO_BRONZE_CUSTOMER_TASK RESUME;
